### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by hmc-cs-ssedky** [hmc-cs-ssedky/ScriptEditor#3]

**Comment by hmc-cs-ssedky** [comment]
- [x] Schedule initial meeting with Prof. Ben

- [x] Meet with Prof. Ben to discuss project overview.

- [x] Complete all parts of the project plan document (found [here](https://docs.google.com/document/d/1cW2egAAJ_j4OOtsDcbZKKq1vwm0ng-jf_Qz4RePnoSM/edit?ts=58a79506))

- [x] Submit project plan.
